apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
  labels:
    app: targeting-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:CHANGE_ME@postgres-vm.db-subnet.togglemaster-vcn.oraclevcn.com:5432/targeting_db"
  AUTH_SERVICE_URL: "http://auth-service.togglemaster.svc.cluster.local"
