apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: togglemaster
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:15-alpine
        env:
        - name: PGPASSWORD
          value: "togglepass123"
        command: ["psql"]
        args: 
        - "-h"
        - "postgres"
        - "-U"
        - "togglemaster_user"
        - "-d"
        - "solidary_db"
        - "-c"
        - |
          CREATE TABLE IF NOT EXISTS ngos (
              id SERIAL PRIMARY KEY,
              name VARCHAR(150) NOT NULL,
              email VARCHAR(100) UNIQUE NOT NULL,
              cause VARCHAR(100) NOT NULL,
              city VARCHAR(100) NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
          );
          CREATE TABLE IF NOT EXISTS donations (
              id SERIAL PRIMARY KEY,
              ngo_id INT NOT NULL,
              amount NUMERIC(10, 2) NOT NULL,
              donor_name VARCHAR(100) NOT NULL,
              status VARCHAR(20) NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
          );
          INSERT INTO ngos (name, email, cause, city) VALUES 
          ('Anjos de Patas', 'contato@anjosdepatas.org', 'Proteção Animal', 'Osasco'),
          ('Educa Mais', 'info@educamais.org', 'Educação', 'São Paulo')
          ON CONFLICT (email) DO NOTHING;
      restartPolicy: OnFailure
  backoffLimit: 4
