apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: togglemaster
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE ngo_db;
      CREATE DATABASE donation_db;
      GRANT ALL PRIVILEGES ON DATABASE ngo_db TO $POSTGRES_USER;
      GRANT ALL PRIVILEGES ON DATABASE donation_db TO $POSTGRES_USER;
    EOSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: togglemaster
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "ngo_db"
        - name: POSTGRES_USER
          value: "togglemaster_user"
        - name: POSTGRES_PASSWORD
          value: "togglepass123"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: postgres-storage
        emptyDir: {}
      - name: init-scripts
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: togglemaster
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
