apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  namespace: togglemaster
type: Opaque
data:
  # O valor deve ser a sua New Relic License Key codificada em base64
  # Exemplo: echo -n "SUA_CHAVE" | base64
  license-key: 4692ac4c0e3799d8f68e6ac2c92a4de73f8bNRAL
