apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  namespace: togglemaster
type: Opaque
data:
  # O valor deve ser a sua New Relic License Key codificada em base64
  # Exemplo: echo -n "SUA_CHAVE" | base64
  license-key: REVCQUY1MEE0MTQwQUI1NzU2NzVCRDhGRDQxMDk3ODZFM0VBRDNBOUJBMDNBREU1N0I4NkE2RDBFRDg0QzUzRA==
  # OTLP headers: api-key=<SUA_CHAVE> codificado em base64
  # Exemplo: echo -n "api-key=SUA_CHAVE" | base64
  otlp-headers: YXBpLWtleT0zNDlCNzk0MTFGQjZEQjM1MjdEQzhCMTAwRDVENDEwOEI4OTk0NEIyN0EzNDY0QkIzREUxOTZBNUJFMjQzNkZD
