apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  namespace: togglemaster
type: Opaque
data:
  # O valor deve ser a sua New Relic License Key codificada em base64
  # Exemplo: echo -n "SUA_CHAVE" | base64
  license-key: REPLACE_WITH_BASE64_LICENSE_KEY
