apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: postgres://togglemaster_user:togglepass123@10.0.5.147:5432/auth_db
  MASTER_KEY: supersecretkey