apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
  labels:
    app: auth-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:CHANGE_ME@postgres-vm.db-subnet.togglemaster-vcn.oraclevcn.com:5432/auth_db?sslmode=disable"
  MASTER_KEY: "CHANGE_ME"
