#cloud-config

packages:
  - postgresql-server
  - postgresql

runcmd:

  # Configurar Firewall (Oracle Linux 9)
  - sudo firewall-cmd --permanent --add-port=5432/tcp
  - sudo firewall-cmd --reload

  # Inicializar PostgreSQL principal
  - sudo postgresql-setup --initdb

  # Habilitar acesso remoto
  - sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/pgsql/data/postgresql.conf

  # Liberar acesso da VCN (10.0.0.0/16)
  - echo "host all all 10.0.0.0/16 md5" | sudo tee -a /var/lib/pgsql/data/pg_hba.conf

  # Iniciar servico
  - sudo systemctl enable postgresql
  - sudo systemctl start postgresql

  # Criar usuario e bancos
  - sudo -u postgres psql -c "CREATE USER togglemaster_user WITH PASSWORD 'togglepass123';"

  # Bancos dos microsservicos SolidaryTech
  - sudo -u postgres psql -c "CREATE DATABASE ngo_db OWNER togglemaster_user;"
  - sudo -u postgres psql -c "CREATE DATABASE donation_db OWNER togglemaster_user;"

  # Bancos dos microsservicos ToggleMaster
  - sudo -u postgres psql -c "CREATE DATABASE auth_db OWNER togglemaster_user;"
  - sudo -u postgres psql -c "CREATE DATABASE flags_db OWNER togglemaster_user;"
  - sudo -u postgres psql -c "CREATE DATABASE targeting_db OWNER togglemaster_user;"

  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ngo_db TO togglemaster_user;"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE donation_db TO togglemaster_user;"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE auth_db TO togglemaster_user;"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE flags_db TO togglemaster_user;"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE targeting_db TO togglemaster_user;"

  # Criar tabelas iniciais no ngo_db
  - sudo -u postgres psql -d ngo_db -c "CREATE TABLE IF NOT EXISTS ngos (id SERIAL PRIMARY KEY, name VARCHAR(150) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, cause VARCHAR(100) NOT NULL, city VARCHAR(100) NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);"
  - sudo -u postgres psql -d ngo_db -c "INSERT INTO ngos (name, email, cause, city) VALUES ('Anjos de Patas', 'contato@anjosdepatas.org', 'Protecao Animal', 'Osasco'), ('Educa Mais', 'info@educamais.org', 'Educacao', 'Sao Paulo') ON CONFLICT (email) DO NOTHING;"

  # Criar tabelas iniciais no donation_db
  - sudo -u postgres psql -d donation_db -c "CREATE TABLE IF NOT EXISTS donations (id SERIAL PRIMARY KEY, ngo_id INT NOT NULL, amount NUMERIC(10, 2) NOT NULL, donor_name VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);"
