apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "10.0.5.147"
  DB_PORT: "5432"
  DB_USER: "togglemaster_user"
  DB_PASSWORD: "togglepass123"