apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
  labels:
    app: analytics-service
type: Opaque
stringData:
  AWS_SQS_URL: "CHANGE_ME"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"
