apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-service
  namespace: togglemaster
  labels:
    app: donation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation-service
  template:
    metadata:
      labels:
        app: donation-service
    spec:
      containers:
      - name: donation-service
        image: sa-saopaulo-1.ocir.io/grqkmwwimskh/togglemaster/donation-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: donation-service-secret
              key: DATABASE_URL
        - name: AWS_SQS_URL
          value: "https://sqs.us-east-1.amazonaws.com/123456789012/donation-queue"
        - name: AWS_REGION
          value: "us-east-1"
        # OTel para Go requer instrumentação no código, mas as envs ajudam o SDK
        - name: OTEL_SERVICE_NAME
          value: "donation-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://otlp.nr-data.net"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: license-key
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "api-key=$(NEW_RELIC_LICENSE_KEY)"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: togglemaster
spec:
  selector:
    app: donation-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
---
apiVersion: v1
kind: Secret
metadata:
  name: donation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://togglemaster_user:togglepass123@postgres-vm.dbsubnet.togglemastervcn.oraclevcn.com:5432/donations_db"
