apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
  labels:
    app: evaluation-service
type: Opaque
stringData:
  REDIS_URL: "redis://redis-vm.dbsubnet.togglemastervcn.oraclevcn.com:6379"
  FLAG_SERVICE_URL: "http://flag-service.togglemaster.svc.cluster.local"
  TARGETING_SERVICE_URL: "http://targeting-service.togglemaster.svc.cluster.local"
  SERVICE_API_KEY: "CHANGE_ME"
  OCI_QUEUE_ENDPOINT: "https://cell-1.queue.messaging.sa-saopaulo-1.oci.oraclecloud.com"
  OCI_QUEUE_ID: "ocid1.queue.oc1.sa-saopaulo-1.amaaaaaayge6yiaaavea4whls4o5dbtja7qnvchoxj353sqtlmoakofwa4zq"
