apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
  labels:
    app: evaluation-service
type: Opaque
stringData:
  # IP PRIVADO DO REDIS CORRIGIDO
  REDIS_URL: "redis://10.0.5.250:6379"
  FLAG_SERVICE_URL: "http://flag-service.togglemaster.svc.cluster.local"
  TARGETING_SERVICE_URL: "http://targeting-service.togglemaster.svc.cluster.local"
  # VOCÊ DEVE CRIAR UMA CHAVE NO AUTH-SERVICE E COLOCAR AQUI
  SERVICE_API_KEY: "tm_key_bdd25a2100e176879672dda912257d456869804290d35100fb41e29ce9867b32"
  # ENDPOINT E OCID CORRETOS CONFORME O ERRO DO LOG (404 NotAuthorizedOrNotFound)
  # O log indica que o OCID abaixo NÃO é encontrado ou autorizado.
  # Você deve substituir pelo OCID REAL da fila que aparece no console OCI.
  OCI_QUEUE_ENDPOINT: "https://cell-1.queue.messaging.sa-saopaulo-1.oci.oraclecloud.com"
  OCI_QUEUE_ID: "ocid1.queue.oc1.sa-saopaulo-1.amaaaaaayge6yiaaavea4whls4o5dbtja7qnvchoxj353sqtlmoakofwa4zq"
