apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
  labels:
    app: evaluation-service
type: Opaque
stringData:
  REDIS_URL: "redis://redis-vm.db-subnet.togglemaster-vcn.oraclevcn.com:6379"
  FLAG_SERVICE_URL: "http://flag-service.togglemaster.svc.cluster.local"
  TARGETING_SERVICE_URL: "http://targeting-service.togglemaster.svc.cluster.local"
  SERVICE_API_KEY: "CHANGE_ME"
  AWS_SQS_URL: "CHANGE_ME"
  AWS_REGION: "us-east-1"
