apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
spec:
  type: LoadBalancer
  selector:
    app: evaluation-service
  ports:
    - name: http
      port: 80
      targetPort: 8004
      protocol: TCP
